#!/usr/bin/env node
/* ═══════════════════════════════════════════════════════════════════════
   SwiftChannels — language page builder
   ───────────────────────────────────────────────────────────────────────
   index.html is the single source of truth, in English.
   This script opens it in a real browser, asks the site's own translation
   engine to switch language, and saves the result as a static page:

       fr/index.html   es/index.html   de/index.html   ar/index.html

   Each generated page carries its own <html lang>, canonical, hreflang set
   and Open Graph locale, so Google indexes the five versions separately.
   sitemap.xml is rewritten to match.

   Run it after ANY change to index.html or assets/i18n.js:

       node build.js

   Requires Playwright once:  npm install playwright
   ═══════════════════════════════════════════════════════════════════════ */

const { chromium } = require('playwright');
const fs   = require('fs');
const path = require('path');

const SITE  = 'https://swiftchannels.com';
const ROOT  = __dirname;
const LANGS = [
  { code:'en', dir:'ltr', folder:'',   ogLocale:'en_GB' },
  { code:'fr', dir:'ltr', folder:'fr', ogLocale:'fr_FR' },
  { code:'es', dir:'ltr', folder:'es', ogLocale:'es_ES' },
  { code:'de', dir:'ltr', folder:'de', ogLocale:'de_DE' },
  { code:'it', dir:'ltr', folder:'it', ogLocale:'it_IT' },
  { code:'nl', dir:'ltr', folder:'nl', ogLocale:'nl_NL' }
];

const urlFor = f => f ? `${SITE}/${f}/` : `${SITE}/`;

/* Which dictionary files exist, and the page each extra belongs to. */
const DATA = ['assets/i18n', 'assets/channels-i18n', 'assets/install-i18n',
              'assets/legal-i18n', 'assets/order-i18n'];
const EXTRA_FOR = {
  'channels.html': 'assets/channels-i18n',
  'install.html':  'assets/install-i18n',
  'legal.html':    'assets/legal-i18n',
  'order.html':    'assets/order-i18n'
};

/* Read each dictionary file by running it, then write one file per language.
   Running it is the only way to be sure we split exactly what the file
   defines — the alternative is parsing JavaScript with a regular expression,
   which is how translations quietly go missing. */
async function splitDictionaries(browser) {
  const out = {};
  for (const base of DATA) {
    const page = await browser.newPage();
    await page.goto('about:blank');
    await page.evaluate(langs => {
      window.I18N = {};
      langs.forEach(l => { window.I18N[l] = {}; });
    }, LANGS.filter(l => l.folder).map(l => l.code));
    await page.addScriptTag({ path: path.join(ROOT, base + '.js') });
    out[base] = await page.evaluate(() => JSON.parse(JSON.stringify(window.I18N)));
    await page.close();

    for (const L of LANGS.filter(l => l.folder)) {
      const dict = out[base][L.code] || {};
      const body = 'window.I18N=window.I18N||{};'
                 + 'window.I18N.' + L.code + '=window.I18N.' + L.code + '||{};'
                 + 'Object.assign(window.I18N.' + L.code + ','
                 + JSON.stringify(dict) + ');\n';
      fs.writeFileSync(path.join(ROOT, base + '.' + L.code + '.js'), body, 'utf8');
    }
    const n = Object.keys(out[base][LANGS[1].code] || {}).length;
    console.log('  split ' + base + '.js  → 5 files, ' + n + ' keys each');
  }

  /* The engine on its own. Everything above the lone `};` is the data
     literal; everything below it is the code. */
  const src = fs.readFileSync(path.join(ROOT, 'assets/i18n.js'), 'utf8');
  const lines = src.split('\n');
  const cut = lines.findIndex(l => l === '};');
  if (cut < 0) throw new Error('assets/i18n.js: cannot find the end of the data block');
  const core = '/* Generated by build.js from assets/i18n.js — do not edit. */\n'
             + 'window.I18N = window.I18N || {};\n'
             + lines.slice(cut + 1).join('\n');
  fs.writeFileSync(path.join(ROOT, 'assets/i18n.core.js'), core, 'utf8');
  console.log('  wrote assets/i18n.core.js  (' + (core.length / 1024).toFixed(0) + ' KB, was '
              + (src.length / 1024).toFixed(0) + ' KB)');
  return out;
}

(async () => {
  const browser = await chromium.launch();
  const built = [];
  const DICTS = await splitDictionaries(browser);

  /* Each source page and the marker that says it has finished booting. */
  const PAGES = [
    { file:'index.html', ready:() => window.i18n && document.querySelector('.plan') },
    { file:'legal.html', ready:() => window.i18n && document.querySelector('.who') },
    { file:'channels.html', ready:() => window.i18n && document.querySelector('.ct') },
    { file:'install.html', ready:() => window.i18n && document.querySelector('.ri') },
    { file:'order.html', ready:() => window.i18n && document.getElementById('send') },
    { file:'thank-you.html', ready:() => window.i18n && document.querySelector('.up') }
  ];

  for (const L of LANGS.filter(l => l.folder))
  for (const SRC of PAGES) {
    const page = await browser.newPage();
    const errors = [];
    page.on('pageerror', e => errors.push(e.message));

    await page.goto('file://' + path.join(ROOT, SRC.file));
    await page.waitForFunction(SRC.ready);

    /* The page now ships no dictionary of its own, so give it this one
       language before asking the engine to translate. DICT inside the engine
       is the same object, so a property added here is visible to it. */
    const extraFile = EXTRA_FOR[SRC.file] || null;
    await page.evaluate(([lang, main, extra]) => {
      window.I18N = window.I18N || {};
      window.I18N[lang] = Object.assign({}, main || {}, extra || {});
    }, [L.code, DICTS['assets/i18n'][L.code],
        extraFile ? DICTS[extraFile][L.code] : null]);

    /* the site's own engine does the translating — one implementation, not two */
    await page.evaluate(l => window.i18n.apply(l, false), L.code);
    await page.waitForTimeout(350);

    const html = await page.evaluate(cfg => {
      const { code, dir, folder, ogLocale, site, langs, file, dicts } = cfg;
      const abs = f => f ? site + '/' + f + '/' : site + '/';

      document.documentElement.setAttribute('lang', code);
      document.documentElement.setAttribute('dir', dir);

      /* The page now lives one folder down, so relative paths need ../ —
         except links to pages that also have a copy in this folder. */
      const SAME_FOLDER = ['legal.html', 'index.html', 'channels.html', 'install.html',
                          'order.html', 'thank-you.html'];
      document.querySelectorAll('[src],[href]').forEach(el => {
        for (const attr of ['src','href']) {
          const v = el.getAttribute(attr);
          if (!v) continue;
          if (/^(https?:|mailto:|tel:|#|\/|\.\.\/|\.\/|data:)/.test(v)) continue;
          if (SAME_FOLDER.includes(v.split('#')[0])) continue;
          el.setAttribute(attr, '../' + v);
        }
      });

      /* Structured data. The path rewriter above only touches src/href
         attributes, and these URLs live inside JSON — so repoint the ones
         that name a page of this site at this language's copy, leave asset
         URLs alone, and stamp the language. */
      document.querySelectorAll('script[type="application/ld+json"]').forEach(el => {
        const page = /^https:\/\/swiftchannels\.com\/((?:[a-z-]+\.html)?(?:#.*)?)$/;
        const walk = o => {
          if (Array.isArray(o)) return o.map(walk);
          if (o && typeof o === 'object') {
            /* Organization, WebSite and Product are one entity each, shared by
               every language, so their @id stays global — six @ids for one
               company would split the entity. Page-scoped nodes are the ones
               that must name this language's copy. */
            const SCOPED = ['WebPage','BreadcrumbList','ListItem'];
            const pageScoped = SCOPED.includes(o['@type']) || o['@type'] === undefined;
            const out = {};
            for (const k of Object.keys(o)) {
              const v = o[k];
              if (k === 'inLanguage') { out[k] = code; continue; }
              if (typeof v === 'string' && ['@id','url','item'].includes(k) && pageScoped) {
                const m = page.exec(v);
                out[k] = m ? abs(folder) + m[1] : v;
                continue;
              }
              out[k] = walk(v);
            }
            return out;
          }
          return o;
        };
        try {
          el.textContent = JSON.stringify(walk(JSON.parse(el.textContent)), null, 2);
        } catch (e) { /* leave malformed JSON exactly as it was */ }
      });

      /* head: canonical, hreflang, Open Graph */
      const head = document.head;
      head.querySelectorAll('link[rel="canonical"],link[rel="alternate"]').forEach(e => e.remove());

      const canon = document.createElement('link');
      canon.rel = 'canonical';
      canon.href = abs(folder) + file;
      head.appendChild(canon);

      langs.forEach(l => {
        const a = document.createElement('link');
        a.rel = 'alternate';
        a.hreflang = l.code;
        a.href = abs(l.folder) + file;
        head.appendChild(a);
      });
      const xd = document.createElement('link');
      xd.rel = 'alternate';
      xd.hreflang = 'x-default';
      xd.href = abs('') + file;
      head.appendChild(xd);

      const setMeta = (sel, val) => {
        const m = head.querySelector(sel);
        if (m) m.setAttribute('content', val);
      };
      setMeta('meta[property="og:url"]', abs(folder) + file);
      setMeta('meta[property="og:locale"]', ogLocale);
      setMeta('meta[property="og:title"]', document.title);
      const desc = head.querySelector('meta[name="description"]');
      if (desc) {
        setMeta('meta[property="og:description"]', desc.getAttribute('content'));
        setMeta('meta[name="twitter:description"]', desc.getAttribute('content'));
      }
      setMeta('meta[name="twitter:title"]', document.title);

      /* switcher: links relative to this folder, active flag marked */
      document.querySelectorAll('.lang-b').forEach(a => {
        const to = a.getAttribute('data-lang');
        const target = langs.find(l => l.code === to);
        const base = target.folder ? '../' + target.folder + '/' : '../';
        a.setAttribute('href', base + file);
        a.setAttribute('aria-current', String(to === code));
      });

      /* the dictionaries this page actually needs, and only those */
      const core = document.querySelector('script[src$="i18n.core.js"]');
      if (core) {
        [dicts.main, dicts.extra].filter(Boolean).forEach(src => {
          const t = document.createElement('script');
          t.src = src;
          core.parentNode.insertBefore(t, core);
        });
      }

      /* tell the engine this page is already translated */
      const flag = document.createElement('script');
      flag.textContent = "window.PAGE_LANG='" + code + "';";
      const i18nScript = document.querySelector('script[src$="i18n.core.js"]');
      i18nScript.parentNode.insertBefore(flag, i18nScript);

      /* reveal classes and the generated order reference are runtime noise */
      document.querySelectorAll('.rv.in').forEach(e => e.classList.remove('in'));
      /* the card flow builds its own dots and state at runtime */
      const fd = document.getElementById('flowDots');
      if (fd) fd.innerHTML = '';
      document.querySelectorAll('.fc.is-on').forEach(e => e.classList.remove('is-on'));
      document.querySelectorAll('.flow.touched').forEach(e => e.classList.remove('touched'));
      document.querySelectorAll('.fc[role="listitem"]').forEach(e => e.removeAttribute('role'));
      const ref = document.getElementById('ref');
      if (ref) ref.textContent = '—';

      return '<!DOCTYPE html>\n' + document.documentElement.outerHTML + '\n';
    }, { code:L.code, dir:L.dir, folder:L.folder, ogLocale:L.ogLocale, site:SITE, langs:LANGS,
         file: SRC.file === 'index.html' ? '' : SRC.file,
         dicts: {
           main:  '../assets/i18n.' + L.code + '.js',
           extra: extraFile ? '../' + extraFile + '.' + L.code + '.js' : null
         } });

    if (errors.length) {
      console.error(`  ✗ ${L.code}/${SRC.file}: ${errors.join(' | ')}`);
      process.exitCode = 1;
    }

    const dir = path.join(ROOT, L.folder);
    fs.mkdirSync(dir, { recursive: true });
    fs.writeFileSync(path.join(dir, SRC.file), html, 'utf8');
    console.log(`  ✓ ${L.folder}/${SRC.file}  (${(html.length/1024).toFixed(0)} KB)`);
    built.push(L.code + '/' + SRC.file);
    await page.close();
  }

  await browser.close();

  /* ── sitemap with hreflang alternates on every entry ── */
  const today = fs.statSync(path.join(ROOT,'index.html')).mtime.toISOString().slice(0,10);
  const alternates = LANGS.map(l =>
    `      <xhtml:link rel="alternate" hreflang="${l.code}" href="${urlFor(l.folder)}"/>`
  ).join('\n') +
  `\n      <xhtml:link rel="alternate" hreflang="x-default" href="${urlFor('')}"/>`;

  const legalAlternates = LANGS.map(l =>
    `      <xhtml:link rel="alternate" hreflang="${l.code}" href="${urlFor(l.folder)}legal.html"/>`
  ).join('\n') +
  `\n      <xhtml:link rel="alternate" hreflang="x-default" href="${urlFor('')}legal.html"/>`;

  const installAlternates = LANGS.map(l =>
    `      <xhtml:link rel="alternate" hreflang="${l.code}" href="${urlFor(l.folder)}install.html"/>`
  ).join('\n') +
  `\n      <xhtml:link rel="alternate" hreflang="x-default" href="${urlFor('')}install.html"/>`;

  const channelsAlternates = LANGS.map(l =>
    `      <xhtml:link rel="alternate" hreflang="${l.code}" href="${urlFor(l.folder)}channels.html"/>`
  ).join('\n') +
  `\n      <xhtml:link rel="alternate" hreflang="x-default" href="${urlFor('')}channels.html"/>`;

  const entries = LANGS.map(l => `  <url>
    <loc>${urlFor(l.folder)}</loc>
${alternates}
    <lastmod>${today}</lastmod>
    <changefreq>weekly</changefreq>
    <priority>${l.folder ? '0.9' : '1.0'}</priority>
  </url>`).join('\n') + '\n' +
  LANGS.map(l => `  <url>
    <loc>${urlFor(l.folder)}legal.html</loc>
${legalAlternates}
    <lastmod>${today}</lastmod>
    <changefreq>yearly</changefreq>
    <priority>0.3</priority>
  </url>`).join('\n');

  const extra = '\n' + LANGS.map(l => `  <url>
    <loc>${urlFor(l.folder)}channels.html</loc>
${channelsAlternates}
    <lastmod>${today}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.7</priority>
  </url>`).join('\n') + '\n' +
  LANGS.map(l => `  <url>
    <loc>${urlFor(l.folder)}install.html</loc>
${installAlternates}
    <lastmod>${today}</lastmod>
    <changefreq>monthly</changefreq>
    <priority>0.6</priority>
  </url>`).join('\n');

  fs.writeFileSync(path.join(ROOT,'sitemap.xml'),
`<?xml version="1.0" encoding="UTF-8"?>
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9"
        xmlns:xhtml="http://www.w3.org/1999/xhtml">
${entries}${extra}
</urlset>
`, 'utf8');
  console.log('  ✓ sitemap.xml');
  console.log(`\nBuilt ${built.length} pages. Commit and push.`);
})();
